name: apptraicay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/welcome2.jpg
    - assets/Welcome.jpg
    - assets/welcome1.jpg
    - assets/dua_hau.jpg
    - assets/tao_do.jpg
    - assets/chuoi.jpg
    - assets/cam_sanh.jpg
    - assets/xoai_cat.jpg
