name: apptraicay
description: "Nhập hàng bằng Excel"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  excel: ^2.0.7
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  file_selector: ^1.0.3
  qr_flutter: ^4.0.0
  fl_chart: ^0.66.0
  intl: ^0.18.1 
  mime: any
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/welcome2.jpg
    - assets/Welcome.jpg
    - assets/welcome1.jpg
    